import { DeliveryOrderConfig, StoreServiceArea } from "./shop-list";


export interface BasketObj {
  items: Array<OrderItem>;
  storeName: string;
  storeCode: string;
  serviceArea: StoreServiceArea[];
  totalItemsCount:number;
  deliveryOrderConfig:DeliveryOrderConfig;  //this is used to perform precheck validation
}

export interface OrderItem {
  orderItemId:string,// id will  be generated by firebase.
  name: string;
  quantity: number;
  productImageUrl: string;
  pricePerQuantity: number;
  totalPrice: number;
  productId: string;
}

export interface BasketFooterObj {
  totalItemCount: number;
  totalBasket: number;
  storecode: string;
}
